name: ci
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'master'

jobs:
  docker:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Webpack Linode Sync
        id: docker_build_webpack_linode_sync
        uses: docker/build-push-action@v2
        with:
          context: ./webpack-linode-sync
          platforms: linux/amd64
          push: true
          tags: tmuntaner/webpack-linode-sync:latest
      - name: Craft CMS nginx
        id: docker_build_craftcms_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./craftcms-nginx
          platforms: linux/amd64
          push: true
          tags: tmuntaner/craftcms-nginx:latest
      - name: Craft CMS php-fpm
        id: docker_build_craftcms_php_fpm
        uses: docker/build-push-action@v2
        with:
          context: ./craftcms-php-fpm
          platforms: linux/amd64
          push: true
          tags: tmuntaner/craftcms-php-fpm:latest
